filebeat.inputs:
- type:  log
  id: my-filestream-id
  enabled: true
  paths:
    - /usr/share/filebeat/my-log/**/*.log
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'  # 识别以日期格式开头的行
  multiline.negate: true
  multiline.match: after
  fields:
    app: weike_rent

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  
setup.kibana:

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - dissect:
      tokenizer: "[%{timestamp}][%{log_type}][%{thread_id}] %{message}"
      field: "message"
      target_prefix: "log"