version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.3.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      # 设置集群名称
      cluster.name: elasticsearch
      # 以单一节点模式启动
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ${PATH}/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ${PATH}/elasticsearch/data:/usr/share/elasticsearch/data
      - ${PATH}/elasticsearch/logs:/usr/share/elasticsearch/logs
    networks:
      - elk

  logstash:
    image: logstash:7.3.2
    container_name: logstash
    restart: always
    ports:
      - "4560:4560"
    volumes:
      - ${PATH}/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${PATH}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: kibana:7.3.2
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      # kibana在elasticsearch启动之后再启动
      - elasticsearch
    environment:
      #设置系统语言文中文
      I18N_LOCALE: zh-CN
      # 访问域名
      # SERVER_PUBLICBASEURL: https://kibana.cloud.com
    volumes:
      - ${PATH}/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elk

networks:
    elk:
        name: elk
        driver: bridge
