server.name: kibana
server.host: "0.0.0.0"
# server.publicBaseUrl: "http://47.106.134.15:5601"  # 这里地址改为你访问kibana的地址，不能以 / 结尾
elasticsearch.hosts: [ "http://47.106.134.15:9200" ] # http://www.zhengqingya.com:9200 TODO 修改为自己的ip
elasticsearch.username: "elastic"  # es账号
elasticsearch.password: "123456"   # es密码
xpack.monitoring.ui.container.elasticsearch.enabled: true
i18n.locale: zh-CN # 中文